project:
  type: website

website:
  title: "TAEEUNCHOI"
  navbar:
    right:
      - href: about.qmd
        text: "ABOUT"
      - href: contact.qmd
        text: "CONTACT"
  page-footer:
    center: "© 2025 Tae Eun Choi"

format:
  html:
    theme: minty
    css: styles.css
    toc: false
    page-layout: full
    mainfont: "Inter"
    headingfont: "Playfair Display"
    monofont: "Fira Code"